version: '3.9'
services:
  mf_drawer:
    build: ./mf_drawer
    ports:
      - "3002:3002"
    networks:
      - frontend-network

  mf_videos:
    build: ./mf_videos
    ports:
      - "3003:3003"
    networks:
      - frontend-network

  bff:
    build: ./bff
    ports:
      - "3001:3001"
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
